version: '3'

services:
  influxdb:
    image: influxdb:latest
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  telegraf:
    image: telegraf:latest
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxv2.env
    dns:
      1.1.1.1


  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9999:9999"
    volumes:
      - ./mosquitto.conf:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  influxdbv2:
