version: '3'

services:
  influxdb:
    image: influxdb:latest
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  telegraf:
    image: telegraf:latest
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxv2.env
    dns:
      1.1.1.1


  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "9001:9001"
      - "9002:9002"
    volumes:
      - ./config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    dns:
      1.1.1.1
volumes:
  influxdbv2:


# NNSXS.5XUS5DPOO2ZRQNHWTKE27VHYVXU6LPCWASGO7BY.RCE5T4SF52CCZ6VCFHXILDHOSF2UUYHSL25V2BNFZRZLN4C7LKKA